### ISSUE TITLE
Implement Stripes Ephemeral Keys

### ISSUE THREAD

**Issue by anthonycastelli** [vapor-community/stripe-provider#12]
Currently they don't have any documentation on this, however the new iOS SDK requires it.

**Comment by Andrewangeta** [comment]
Maybe we should check other backend SDKs and see if and how they do it. Otherwise we should contact Stripe for some guidance.

**Comment by anthonycastelli** [comment]
I just reached out to them again. They said they were hoping to have the documentation done sometime by the end of the month, if they got it all working. From the sound of it, this is all experimental, but doesn't make sense as to why they would release it.

**Comment by geeksweep** [comment]
thanks guys! Yeah if you want to use their built in elements, along with the CustomerContext, you need to generate this key so the context can do all the updating to the customer you have stored in your DB. I talked with @anthonycastelli about this this evening.

**Comment by damirstuhec** [comment]
Hey guys! I just ran into this as well. As @geeksweep said, generating the ephemeral key is now required. Do we have any updates on this? Is there a way I can help?

**Comment by anthonycastelli** [comment]
Currently the only way around this is to use an older version of the Stripe library for iOS and Android. Currently Stripe doesn't have documentation on this new system so i'm completely in the dark with implementing it. I haven't had much time to sit down and start going through Stripe's other libraries and figure out what they are doing.

**Comment by damirstuhec** [comment]
@anthonycastelli Yeah, I see. You probably saw this already but seems like their official libraries for other languages like `php` already have support for ephemeral key creation: https://github.com/stripe/stripe-php/search?utf8=%E2%9C%93&q=EphemeralKey&type=. Maybe this can help?

**Comment by damirstuhec** [comment]
Or this from their ruby lib: https://github.com/stripe/example-ios-backend/blob/master/web.rb#L18, https://github.com/stripe/stripe-ruby/blob/234b0809bfd737f7a8ddf215d23e15cab6efc741/lib/stripe/ephemeral_key.rb.

**Comment by Andrewangeta** [comment]
I think it'll be best if we just wait for official docs. We don't wanna implement it and then have to go back and change it.

**Comment by damirstuhec** [comment]
@Andrewangeta @anthonycastelli I just talked with Stripe engineer on their freenode irc chat, and he said that they do not really intend to add a documentation for Ephemeral Keys, since the implementation is so simple and can be easily replicated based on the existing libraries that are officially supported (the ones I linked above).

So do we still want wait for the docs (which might not happen soon) or should we just go ahead and implement this based on the implementations in other libs?

**Comment by vzsg** [comment]
Isn't it just a simple HTTP POST request? The Ruby version seems very simple.

**Comment by damirstuhec** [comment]
@vzsg Seems like it, yes.

**Comment by Andrewangeta** [comment]
If they’re dragging their feet on the docs, I think we can go ahead and implement this feature if the other libraries are straight forward.

**Comment by damirstuhec** [comment]
Anyone on this already or should I take a stab at it?

**Comment by anthonycastelli** [comment]
@damirstuhec I know I am quite busy right now and just haven't had a chance to really work with this library. If you could submit a PR for it, that would be great!

**Comment by Andrewangeta** [comment]
Oh yea i forgot about this. it seems pretty straight forward. I could try to get it done by tonight, some other projects I’m working on are on hold for now so I’d be free.

**Comment by damirstuhec** [comment]
@Andrewangeta That would be awesome.

**Comment by Andrewangeta** [comment]
Yea I’ll be home in a couple hours and I’ll get started

**Comment by anthonycastelli** [comment]
@Andrewangeta took care of this issue with PR #19
