### ISSUE TITLE
Charges list request fails due to trailing /

### ISSUE THREAD

**Issue by kschins** [vapor-community/stripe-provider#123]
When trying to retrieve a list of all charges for a customer, the network request with Stripe fails due to a trailing / in the URL. v1/charges/ is invalid and should be v1/charges.

According to the Stripe API logs, 

`{
  "error": {
    "message": "Unrecognized request URL (GET: /v1/charges/). If you are trying to list objects, remove the trailing slash. If you are trying to retrieve an object, make sure you passed a valid (non-empty) identifier in your code. Please see https://stripe.com/docs or we can help at https://support.stripe.com/.",
    "type": "invalid_request_error"
  }
}`

**Comment by Andrewangeta** [comment]
@kschins This was fixed in Stripekit [here](https://github.com/vapor-community/stripe-kit/pull/111/files).
You should be able to get the latest patch fix by updating your swift package to the latest.

**Comment by kschins** [comment]
Awesome, thank you!
