### ISSUE TITLE
Additional owners: European issue

### ISSUE THREAD

**Issue by TheSwiftyCoder** [vapor-community/stripe-provider#22]
In Europe, Stripe always requires that you provide information about additional owners of the company and this is documented [here|https://stripe.com/docs/connect/updating-accounts#additional-owners]. You can have up to 4 additional owners as they need anyone owning 25% or more but you don't always have 4.

In the event of 0 additional owners the field still needs to be populated similar to the PHP library:
`"additional_owners"  => ""`

In doing so Stripe doesn't complain about the additional owners fields being populated.

Thanks

**Comment by anthonycastelli** [comment]
@Andrewangeta Is this issue pertinent with Stripe Provider 2.0?

**Comment by Andrewangeta** [comment]
I didn’t account for this as I never understood why this is the case.

**Comment by anthonycastelli** [comment]
Closing this
