### ISSUE TITLE
DecodingError.keyNotFound: Value required for key 'error'.

### ISSUE THREAD

**Issue by tarikstafford** [vapor-community/stripe-provider#33]
func createCustomerId(_ req: Request) throws -> Future<StripeCustomer> {

        return try req.content.decode(StripeCustomer.self).flatMap(to: StripeCustomer.self, { user in
            let response = try req.make(StripeClient.self).customer.create(email: user.email)
            return response
        })
    }
}

Works perfectly, but the response is an error? Not sure where it's catching or missing a value.

**Comment by Andrewangeta** [comment]
In your dashboard no error is thrown correct for the api calls? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tarikstafford** [comment]
Yeah @Andrewangeta 0 errors.

**Comment by Andrewangeta** [comment]
Can you put a breakpoint in StripeRequest.swift at the guard statement for serialized response and check the status code? I was using the customer API and it worked fine. Might be related to the issue here
 https://github.com/vapor/vapor/issues/1610

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Andrewangeta** [comment]
There’s a fix for the status codes being set but it hasn’t been tagged yet is all.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tarikstafford** [comment]
200

![screen shot 2018-04-11 at 6 00 59 pm 2](https://user-images.githubusercontent.com/23550083/38616643-5ee78bfe-3db2-11e8-906f-75dd5e221757.png)

**Comment by Andrewangeta** [comment]
Yea it’s part of the fix in Vapor that wasn’t tagged yet. The response code is 200 but see the type is _.custom_ enum and not the _.ok_ enum.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tarikstafford** [comment]
Cool thanks 👍

**Comment by tarikstafford** [comment]
@Andrewangeta is there a work around I could use for now? I want to test the responses :)

**Comment by Andrewangeta** [comment]
@thelittlelankanprince add this line to `FoundationClient.swift` 
https://github.com/vapor/vapor/blob/8a81713d84b4547c2fe47b21fbdfed0d0ed6d8f3/Sources/Vapor/HTTP/FoundationClient.swift#L80-L81

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tarikstafford** [comment]
@Andrewangeta Hey Andrew,

ran into the following error when fetching ephemeral key:

'Dictionary<String, Any>' required for key 'associated_objects'. (EngineServer.swift:144)

Even though the associated_objects dictionary sent by the stripe API is [String:String].

**Comment by Andrewangeta** [comment]
I’ll take a look

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Andrewangeta** [comment]
@thelittlelankanprince can you paste a print out of the response you're getting from stripe?

**Comment by tarikstafford** [comment]
{
  "id": "ephkey_1CGLNPLmoeRLuBpIcXOe9grJ",
  "object": "ephemeral_key",
  "associated_objects": [
    {
      "type": "customer",
      "id": "cus_Cfg1fQ0U7ok0x4"
    }
  ],
  "created": 1523600835,
  "expires": 1523604435,
  "livemode": false,
  "secret": "ek_test_***FMDY"
}

**Comment by Andrewangeta** [comment]
oh I see, it's an array of dictionary values not a dictionary value itself. This annoys me because Ephemeral Keys are not documented anywhere in their API.

**Comment by Andrewangeta** [comment]
Should have a new version out within the next hour. Stand by.

**Comment by tarikstafford** [comment]
@Andrewangeta cheers!

**Comment by Andrewangeta** [comment]
A vapor update should get you the fix

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tarikstafford** [comment]
@Andrewangeta all sorted!

**Comment by anthonycastelli** [comment]
I think it's safe to close this issue as it will be resolved with Vapor in the future.

**Comment by Andrewangeta** [comment]
Sounds good to me 👍🏽

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
