### ISSUE TITLE
When I update the package I don't get the latest pull

### ISSUE THREAD

**Issue by tarikstafford** [vapor-community/stripe-provider#38]
I even fresh installed with Vapor 3.0 and the stripe provider package and the changes still aren't showing in the stripe folder. Also downloaded the latest zip, and it's the same.

![screen shot 2018-05-10 at 6 46 50 pm](https://user-images.githubusercontent.com/23550083/39871554-dfe5bb86-5482-11e8-9314-370801865dbd.png)
![screen shot 2018-05-10 at 6 49 04 pm](https://user-images.githubusercontent.com/23550083/39871555-e034fa48-5482-11e8-8f0e-a5b782773274.png)

**Comment by tarikstafford** [comment]
don't get this code: 

```
return httpClient.post("\(path)?\(query)", headers: finalHeaders) { (request) in
           try request.content.encode(body)
          }.flatMap(to: SM.self) { (response) -> Future<SM> in
                return try self.serializedResponse(response: response.http, worker: self.httpClient.container.eventLoop)
```

**Comment by Andrewangeta** [comment]
@anthonycastelli do you need to retag a release with the changes? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by anthonycastelli** [comment]
It should of been retagged. Let me just create a new one. 🤷‍♂️

**Comment by anthonycastelli** [comment]
Run `vapor update -y` and see if that works. I tagged it as 2.0.6. If the issue persists, feel free to reopen this issue
