### ISSUE TITLE
Source.type missing crash

### ISSUE THREAD

**Issue by foscomputerservices** [vapor-community/stripe-provider#41]
Quite possibly I've misunderstood something as I'm very new to Stripe.  I've followed the docs on [Checkout](https://stripe.com/docs/checkout) and then the docs on [Creating Charges](https://stripe.com/docs/charges) and successfully retrieved my 'Strip token.  I then make the following call to stripe-provider:

```swift
 return try stripeClient.charge.create(
                amount: Int(amount * 100.0),
                currency: .usd,
                source: stripeToken,
                statementDescriptor: "EFL 1 Year"
            )
```

According to Stripe's website the charge is successful.  However, StripeSource.init crashes in the following code as type is nil.

```swift
        type = try container.decodeIfPresent(SourceType.self, forKey: .type)
        
        switch type! {
        case .card:
```

I've locally made the following changes and all works as expected:

```swift
        type = try container.decodeIfPresent(SourceType.self, forKey: .type)
        
        switch type {
        case .some(.card):
            card = try container.decodeIfPresent(StripeCard.self, forKey: .card)
...
            
        default: break
        }
```

Am I missing something in my call to cause type to be set in the response?

**Comment by Andrewangeta** [comment]
@foscomputerservices So I think I know the problem.
When you make a charge the response returned has a source attached to it _BUT_ that source doesn't have a `type` property but Sources themselves have a type property. I'll reach out to Stripe to see if they can add a type property to the response when completing charges. But for now I think I'll just check the `object` property to see if I can parse the source.

**Comment by anthonycastelli** [comment]
#43 should fix this, right?

**Comment by Andrewangeta** [comment]
@foscomputerservices For now when a source is returned with no type it won't populate until we find a better way to represent a source as anything other than the `Any` type.

**Comment by foscomputerservices** [comment]
Thanks for the fix!!
