### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JamesCoonce** [vapor-community/stripe-provider#63]
There is a lack of documentation or started application that shows how to properly use this package.

**Comment by anthonycastelli** [comment]
What is it you are particularly looking for? Anything specific. There isn't much to it once you initialize it. From that point it's just a matter of the data you wish to fetch or push to stripe.

**Comment by NSMutableString** [comment]
It should indeed by handy if there was some more information about if you need to add some javascript to your page or not. For me the test payment is done directly, but I was expecting to see some stripe screen to enter some test card data. No? Or does this come magically when you will use the live key?
