### ISSUE TITLE
[ ERROR ] DecodingError.valueNotFound - Token issue

### ISSUE THREAD

**Issue by NSMutableString** [vapor-community/stripe-provider#94]
after the payment looks successful, i am redirected to a page where i get following error.

`{"error":true,"reason":"Value of type 'String' required for key 'token'."}`

in the console log, i also see:

`[ ERROR ] DecodingError.valueNotFound: Value of type 'String' required for key 'token'. (ErrorMiddleware.swift:26)`

i launch the stripe popup via the following simple integration they explain at:

[https://stripe.com/docs/checkout#integration-simple](url)

Any idea what step I am missing at this moment?

**Comment by Andrewangeta** [comment]
@NSMutableString Can you paste what code you're using in Vapor?

**Comment by NSMutableString** [comment]
i included the relevant pieces of code. I make use of leaf templating.

[fat-burning.leaf.txt](https://github.com/vapor-community/stripe-provider/files/2937802/fat-burning.leaf.txt)
[routes.swift.txt](https://github.com/vapor-community/stripe-provider/files/2937803/routes.swift.txt)

**Comment by Andrewangeta** [comment]
@NSMutableString change the property to `stripeToken` on your model. that's the property name stripe actually uses. The one in the README is just an example name for a property one might send to the backend via mobile sdk or manipulated in some other way etc.

**Comment by Andrewangeta** [comment]
Also stripe is sending the `stripeToken` via form so it might have to be decoded in a different way than JSON. Not entirely sure I don't use forms very often.

**Comment by NSMutableString** [comment]
Working fine after rename. I assumed i could just copy paste the code from the README. I will send a PR for that. ;-)
